### ISSUE TITLE
Implicit getter and setter for class fields

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#10]
In BBj it is possible to access getter and  setter of a public class field without a need to explicitly declare them.

Example
```vb
CLASS PUBLIC SomeClass
    FIELD PUBLIC BBjString someInstanceString$
CLASSEND

a! = new SomeClass() 
a!.setsomeInstanceString("TEST")


```

**Comment by StephanWald** [comment]
Side note: BBj does during execution cross-compile the structure of a BBj class to Java. So there is a Java class representing methods etc.
We have code that does exactly that. If this is useful we could include it to the project.

**Comment by dhuebner** [comment]
@StephanWald 
Thanks! We will probably not be able o reuse some parts of the generator implementation, but maybe look up some corner cases. 
However getters and setters are  pretty good explained here: https://documentation.basis.cloud/BASISHelp/WebHelp/commands/bbj-commands/field_verb_bbj.htm

Let us do a first draft and see how it works :)

**Comment by dhuebner** [comment]
Works. Note: visibility and `static` not handled yet
