### ISSUE TITLE
BBjServletContext not known

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#129]
See https://documentation.basis.cloud/BASISHelp/WebHelp/bbjobjects/BBxServlet/BBxServlet/BBxServlet.htm
```
CLASS PUBLIC ExampleServlet  
    method public void service(BBxServletContext context!) 
       
        request! = context!.getRequest()
        response! = context!.getResponse()
        session! = request!.getSession()

        s! = response!.getOutputStream()
        s!.write("<html>")
        s!.write("<body>")
        s!.write("<h1>This will print</h1>")
        s!.write("</body>")
        s!.write("</html>")

    METHODEND
CLASSEND
```

**Comment by minionhub** [comment]
@StephanWald what communication tools are you using?

**Comment by StephanWald** [comment]
Adding the USE statement fixes the issue. To be checked: why is this class not recognized in the Classpath? Is it part of BBjInternal? It's contained in BBj.jar.

```
use com.basis.bbj.proxies.servlet.BBxServletContext
```

**Comment by dhuebner** [comment]
@StephanWald 
`com.basis.bbj.proxies.servlet` is not registered as implicit package import.
Following packages are currently implicitly imported: 
`'com.basis.startup.type', 'com.basis.bbj.proxies', 'com.basis.bbj.proxies.sysgui', 'com.basis.bbj.proxies.event', 'com.basis.startup.type.sysgui'`

Should `com.basis.bbj.proxies.servlet` and maybe some additional packages be added as implicit imports?

**Comment by StephanWald** [comment]
Yes it should be added. Where are these implicit imports defined?

**Comment by dhuebner** [comment]
@StephanWald 
In the `JavaInteropService` [here](https://github.com/BBx-Kitchen/bbj-language-server/blob/b7a5cad18aefe1cd22720acd5b37db0a2eee1a3f/bbj-vscode/src/language/java-interop.ts#L18C7-L18C26).
