### ISSUE TITLE
Auto Save upon Run

### ISSUE THREAD

**Issue by LenKrause** [BBx-Kitchen/bbj-language-server#130]
Consider Auto Save upon run of bbj program: (BBj, BUI, or DWC), or implement a setting like eclipse: Auto Save on Run (true/false).

**Comment by minionhub** [comment]
Okay, I will fix this

**Comment by minionhub** [comment]
I finished this feature, Len
What do I have to do now?
Do I have to provide .vsix file or make the pull request?

**Comment by minionhub** [comment]
![image](https://github.com/BBx-Kitchen/bbj-language-server/assets/131043067/ce4cca2a-db3f-4352-9dd8-424f0457fb36)
It is working now on my side.

**Comment by StephanWald** [comment]
@minionhub you can submit a PR, we'll review it then.

**Comment by minionhub** [comment]
Okay sure

**Comment by minionhub** [comment]
I cannot push the code into test branch. @StephanWald

**Comment by minionhub** [comment]
![image](https://github.com/BBx-Kitchen/bbj-language-server/assets/131043067/9a050ac0-9095-4a25-88c0-196fdddeda78)

**Comment by minionhub** [comment]
@LenKrause , Please check this.

**Comment by StephanWald** [comment]
The process for contributing to a public repository in GitHub starts by forking the repository, then pushing the change onto the forked, then creating a pull request onto the original repository. After that comes the role of the project owner to review and take action (merge/decline) of the requested code change.

For more details, please check the below helpful article:

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project

**Comment by minionhub** [comment]
@StephanWald @LenKrause 
I submit the pull request.

**Comment by StephanWald** [comment]
fixed with https://github.com/BBx-Kitchen/bbj-language-server/pull/131, published in v0.0.27
