### ISSUE TITLE
Class ... not in class path

### ISSUE THREAD

**Issue by Der-Dominic** [BBx-Kitchen/bbj-language-server#133]
Hi,

I tried the extension against the newest BBj Version (24.02).
The Installation is fresh and running with a 5-Day Test License.

A simple Statement like `use java.util.HashMap` results in the following error:
`Class java.util.HashMap is not in the class path. bbj`

I tried:
1. Restarting everything (BBjService, VSCode, Extension)
2. Checked out the newest Version from GitHub and Build an own VSXI-Extension to get the newest Release
3. Checked for settings.json in the projects to point to the correct installation.
4. In a simple local BBj-Interpreter the Classes resolve properly

Simple Java Classes are also not resolved in the `examples/using-java.bbj` Source-File in this Repo.

What can I do to debug and/or find why the Imports are missing...

BBj Build Infos:
Platform: Win x64
JDK:  21.0.3.9-hotspot (x64)
Build Date=05/28/2024 17:38
BuildID=1716939522

**Comment by StephanWald** [comment]
A few first things to check:
- when you load a program with the extension ".bbj" - do you see a BBj SysWindow briefly popping up? This would be (for now) the indicator that the extension prepared the BBj service to work with the extension.
- As a result, you should see a schedules task "vscode" and a Classpath "vscode" in Enterprise Manager.

**Comment by Der-Dominic** [comment]
I found the failure.

Two JAR-Files and the "lib" Folder where missing in my extensions Folder which is included through the "vscode" Classpath.

- java-interop.jar
- org.eclipse.lsp4j.jsonrpc-0.20.1.jar

After copying those to the correct folder everything worked.

So for me the sollution is:

1. Clone the repository and build the extension because for some reasons the extension from the marketplace cant execute the command "bbj.initInterop"
2. Copy the required libraries to the java-interop Folder in ~/.vscode/extensions/<beu...>/

**Comment by StephanWald** [comment]
This would only be an issue when you self-compile the extension. When fetching it from marketplace, this should all be done automatically. If it does not, please reopen.
