### ISSUE TITLE
Show parameter names loaded from JSON Javadoc in content assist

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#142]
We already support loading Java information (e.g. Javadoc) from JSON files.

<img width="659" alt="Bildschirmfoto 2024-08-26 um 14 46 53" src="https://github.com/user-attachments/assets/395ec9c7-e4eb-4800-b815-ddd1b1fb9bc4">

We should use this information to show proper parameter names when showing binary Java methods in content assist:

 
<img width="790" alt="Bildschirmfoto 2024-08-26 um 14 47 00" src="https://github.com/user-attachments/assets/25f0708d-b67e-4482-89c7-179d2670d2cf">

We should show `key` and `value` as parameter names instead of `arg0` and `arg1`.

**Comment by StephanWald** [comment]
Added https://github.com/BBx-Kitchen/bbj-language-server/blob/typefox-dev/examples/javadoc/com.basis.bbj.proxies.json to test / discuss the implementation - BBjAPI::openSysGui(alias) and BBjAPI::getFileSystem() and BBjFileSystem::resolvePath(filename) should now work.
@dhuebner  can you please test. In particular, I added http links to the online docs. Is this the right way, should this be HTML, or would it make sense to add a formal "link" field to the JSON that can be composed to a well-formatted display in the popup help?

**Comment by dhuebner** [comment]
@StephanWald 
HTML works well

<img width="771" alt="Bildschirmfoto 2024-09-02 um 11 04 52" src="https://github.com/user-attachments/assets/72dab462-890b-4d92-8960-714fff410da1">


The current state that loads Javadoc from the BBj folder is in the `typefox-dev` branch.

**Comment by StephanWald** [comment]
@dhuebner  I have added a 1st set of JSON files for testing. Most is working as expected, just not the method argument variable names, they still show of as arg0 , arg1 etc...
https://github.com/BBx-Kitchen/bbj-language-server/tree/main/examples/javadoc

![image](https://github.com/user-attachments/assets/01e1962b-d579-4074-81a4-2409b6a2a699)

**Comment by dhuebner** [comment]
The changes are in the `typefox-dev` branch.

**Comment by dhuebner** [comment]
Fix is merged
