### ISSUE TITLE
Javadoc not shown for BBj function

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#146]
Check why Javadoc is not shown for  `GxOptions#getLanguageManager().getLanguageKeys()`

See [ GxOptions#getLanguageKeys() ](https://github.com/BBj-Plugins/BBjGridExWidget/blob/dev/GxOptions.bbj)

**Comment by StephanWald** [comment]
Other sample, self-contained:
```

REM /** 
REM  * Javadoc for TestClass
REM  */
class public TestClass

    REM /** 
    REM  * Javadoc for Method TEST
    REM  */
    method public void test()
        
    methodend


classend

declare TestClass test!

test! = new TestClass()
test!.test()
```

**Comment by dhuebner** [comment]
Fixed in `typefox-dev` branch
