### ISSUE TITLE
read statements are flagged as errors

### ISSUE THREAD

**Issue by LenKrause** [BBx-Kitchen/bbj-language-server#163]
`read (so70, knum=3, dir=0, end=*next)`
![image](https://github.com/user-attachments/assets/8d1f12c7-1522-4cbc-a9df-c7d74e65cacc)
![image](https://github.com/user-attachments/assets/6381bb05-5c26-4ccc-a043-56283cec3e53)
![image](https://github.com/user-attachments/assets/fe48a1b6-8d9b-4eab-9586-8bd70518a2d4)

**Comment by StephanWald** [comment]
```read``` ```write``` and ```find``` are indeed missing. ```read record``` etc are implemented.
