### ISSUE TITLE
print statements that end with a comma followed by a semicolon are flagged as errors

### ISSUE THREAD

**Issue by LenKrause** [BBx-Kitchen/bbj-language-server#165]
```
  if adv < options!.size() then print 'fl', "9", chr(adv), fill(adv, $0a$),; rem  Move down CDS037 grid
```
![image](https://github.com/user-attachments/assets/c3e88eed-c5a4-4ee3-a319-d68e8647d6c7)
![image](https://github.com/user-attachments/assets/092a8e3f-ae54-4f8e-a7d3-5a7a155600fd)

**Comment by StephanWald** [comment]
```print 'fl', "9", chr(adv), fill(adv, $0a$),; rem  Move down CDS037 grid```

**Comment by dhuebner** [comment]
merged
