### ISSUE TITLE
SQLEXEC can have zero arguments

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#177]
The second DIM statement should probably not be flagged as a warning, the reason appears to be the SQLEXEC with no parameter (which is valid):

```
rem regular DIM works:
dim somestring$:"C(10*)"

rem but dim in SQL is flagged:
sqlopen (1)"ChileCompany"
sqlprep (1)"GET TABLE INFO FOR CUSTOMER"
sqlexec (1)
dim x$:sqltmpl(1)
x$=sqlfetch(1)
tpl$ = x.template$
f$=x.filename$
```

![image](https://github.com/user-attachments/assets/f31bb7c2-b438-49ac-9a74-44f57727b4ec)

**Comment by Lotes** [comment]
This one is tricky. I have a solution in mind, but that one is quite complex when you want to implement it. I asked Mark from my team. Maybe he has a better idea.

**Comment by Lotes** [comment]
Done.
