### ISSUE TITLE
SWITCH..CASE : issue with DEFAULT

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#187]
This appears to take issue with CASE DEFAULT

```
switch t$
    case t$=""
        break
    case "TEST"
        break
    case default
        print "default"
        break
swend
```

See https://documentation.basis.cloud/BASISHelp/WebHelp/commands/switch_case_swend_verbs.htm

Appending some continuation with ; to the CASE DEFAULT appears to work -> regression?

```
switch t$
    case t$=""
        break
    case "TEST"
        break
    case default; print "default"
        break
swend
```

**Comment by Lotes** [comment]
Hi @StephanWald ! The documentation does not specify the default case without semicolon.
If this can happen, we should adapt the grammar. Currently we are expecting this semicolon followed by some optional statements.

Do you have evidence from the real world, that this syntax is allowed?

If yes, this should also be part of the documentation, because the current one can lead to the assumption that `case default` is always followed by a semicolon.

**Comment by StephanWald** [comment]
@Lotes In BBj  almost anything can be continued with a semicolon, until you reach the end of the line or until you hit a REM. After a REM, the rest of the line is considered a comment (you cannot end a REM, neither with ; nor with anything else).

So even this is valid, everything in one single line. Not that it's a good idea for readability,  but I've seen people doing it:

```
input i
SWITCH i; CASE 1; PRINT "1"; BREAK; CASE 2; PRINT "2"; BREAK; CASE DEFAULT; PRINT "default"; SWEND
```

**Comment by Lotes** [comment]
@msujew I also tested the following line, which makes the parser use a lot of CPU for a big amount of time (even LSP services get delayed). Can we have a look together? I am also not entirely sure how to arrange the grammar to make this line work (especially with this compound syntax).

```
SWITCH t$;CASE 1; PRINT "1"; BREAK; CASE 2; PRINT "2"; BREAK; CASE DEFAULT; PRINT "default"; SWEND
```

**Comment by StephanWald** [comment]
> SWITCH t$;CASE 1;

Nitpicking detail: you use a String t$ in the SWITCH then compare numbers in the CASE - this does not play with each other and would fail at runtime.

**Comment by dhuebner** [comment]
Should be fixed now
