### ISSUE TITLE
issue when multiplication sign * is not surrounded by whitespace

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#188]
This is flagged as error, but whitespace is optional around mathematical operators:

```
imageW = int(p_width + (2*p_hPadding))
imageH = int(p_height + (2*p_vPadding))
```

**Comment by Lotes** [comment]
@dhuebner The problem here is the symbolic label name:

```
terminal SYMBOLIC_LABEL_NAME: /\*[a-zA-Z]+?/;
```

I think `*p_hPadding` is interpreted as a token instead of a multiplication sign and operand.
I am not sure what we can do here. Maybe split the terminal and validate whether it is a symbolic label name or not. WDYT?
