### ISSUE TITLE
Turn REM to a statement

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#19]
`REM` is a verb in basic and should be handled as a Statement in BBj Grammar instead of hidden lexer rule.

``` 
if x = 1 then print "1" ;  REM comment here
```

**Comment by StephanWald** [comment]
You probably already figured that out, but in a line that is concatenated with a ; everything after REM is considered as a comment. There is no "close comment block", it goes on until the next physical line.
