### ISSUE TITLE
Respect method access-levels

### ISSUE THREAD

**Issue by Lotes** [BBx-Kitchen/bbj-language-server#198]
```
class public Test 

    method private doTest()
    methodend
classend

t! = new Test()
t!.d...
```
![image](https://github.com/user-attachments/assets/f8f1e690-bb52-4297-bb0a-19082716f7f2)

_Originally posted by @StephanWald in https://github.com/BBx-Kitchen/bbj-language-server/issues/74#issuecomment-2340177699_

**Comment by Lotes** [comment]
The [documentation](https://documentation.basis.cloud/BASISHelp/WebHelp/ide/BDT_Code_Completion.htm#Object_Methods_and_Fields) says:

> Only methods with an appropriate access level for the given context will be available - public methods will always be available, private methods are only available when writing code within their class, and protected methods are available within their class and any subclasses.

@dhuebner @StephanWald An idea: We could link the methods without respecting the access-level but add a validation when the access-level is not correct.
The other way would be to exclude symbols from the current scope depending on the context. Then, accessing a private method from an outer class would result in a linking error instead of a validation that the access-level forbids this.
I think the last one is easier to implement, whereas the first gives better messages in my eyes.

**Comment by dhuebner** [comment]
@Lotes 
> We could link the methods without respecting the access-level but add a validation when the access-level is not correct.

I prefer this option as it provides a better user experience. The validation could be like this:
`The method <some_methode> from the type <some_type> is not visible`

**Comment by Lotes** [comment]
@StephanWald I solved the access-levels for methods and fields (instance or static variations) in #200 . We also made an observation, that nested classes are not possible within BBj.
But Java can contain nested classes and I think there might be some gaps in the language server. Can you check how relevant nested classes are for you and create new issues for found gaps? I am thinking of nested classes like `Map.Entry`.

🙏
