### ISSUE TITLE
Support scientific number notation

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#2]
We need a support for scientific notation:
```
1e23
-4.02E-3
```

See [documentation](https://documentation.basis.cloud/BASISHelp/WebHelp/usr/Language_Concepts/numeric_constants_variables_and_arrays.htm)

**Comment by StephanWald** [comment]
I've never seen a program that uses scientific notation in code in >30 years that I'm working with this language. (Output is a different story.)
I suggest postponing this until somebody complains (=never).

**Comment by dhuebner** [comment]
Wait until the issue is reported
