### ISSUE TITLE
Parser problem in context of setopts

### ISSUE THREAD

**Issue by insafuhrmann** [BBx-Kitchen/bbj-language-server#22]
We need to solve the conflict of string replace destination information with method calls, like here for line two:

```
a$=opts
a$(3,1)=ior(a$(3,1),$02$)
setopts A$
```

**Comment by dhuebner** [comment]
@insafuhrmann 
Do you recall where this example comes from? I wonder if `9` in `a$9` as a typo. 
However second line can be parsed now.

**Comment by StephanWald** [comment]
it's a typo. Removed it.

**Comment by dhuebner** [comment]
Fixed already. `setopts` verb is missing and will be handled in  #53
