### ISSUE TITLE
Assume that a string literal is a java.lang.String

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#27]
```vb
foo$ = "TEST"
foo$.charAt(1)  REM <== no linking error here
```

In case of direct string literal assignment assume that the left side is of type `java.lang.String`

**Comment by StephanWald** [comment]
This code snippet is invalid. $ Variables are Strings but do **not** expose the java String methods

READY
>foo$ = "TEST"
>foo$.charAt(1)
!ERROR=20  (Syntax Error: foo$.charAt(1))
>
