### ISSUE TITLE
The hardcoded short constructor BBjAPI() is case insensitive

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#28]
This is valid (though not recommended):

```bbj
sysgui = unt
open (sysgui)"X0"
sysgui! = bbjapi().getSysGui()
```

**Comment by dhuebner** [comment]
@StephanWald 
BBjAPI is not hardcoded, it is linked as a JavaClass `com.basis.bbj.proxies.BBjAPI` and is treated as such. If we handle BBjAPI case insensitive it would mean to add an exceptional case to JavaClass reference handling, which could cause some problems in the future.

We could add a function BBjAPI() to `function.ts` that will be handled case insensitive by default. The return type should be `com.basis.bbj.proxies.BBjAPI`. Unfortunately the type declarations in library are currently not handled at all, but I think it is a good solution. What do you think?

**Comment by dhuebner** [comment]
`BBjAPI` can now be accessed case insensitive.
