### ISSUE TITLE
Allow trailing coma in PRINT statements

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#29]
Following is valid  for `PRINT`, 'WRITE' or `?` statement and mean a line break:

```
PRINT ERR,TCB(5),
REM this is perfectly valid, a line can end with a comma!

```

**Comment by StephanWald** [comment]
small correction: the trailing comman "," with any output statement (PRINT / WRITE / ?) means "do _not_ append a line feed". Irrelevant for supporting the grammar, just want to clarify the meaning.

**Comment by StephanWald** [comment]
For me this still is flagged as error with latest build:

```
X$="TEST"
PRINT X$,

PRINT ERR,TCB(5),
```

**Comment by dhuebner** [comment]
Note: No line break after `,` case
