### ISSUE TITLE
Multiline statement

### ISSUE THREAD

**Issue by dhuebner** [BBx-Kitchen/bbj-language-server#30]
Following is a valid multiline addition and should be supported.
```
rem multiline statement
X! = "TEST"+
: "TEST123"+
: "jhgjgj"

```

Note: `:` is used in the `LabelDecl` parser rule `LabelDecl: ID ':' ;` and in `StringMask` expression rule.

@StephanWald Could you point to the corresponding BBx/BBj documentation? I wonder if it only works with `+` operator or just for all expressions.

**Comment by StephanWald** [comment]
This is not explicitly documented, but the rule is: 
A colon ":" at the beginning of the line means that the line is appended to the previous line "as is"

e.g., the following would be correct (but admittedly silly):

```bbj
P
:R
:INT
: "Hel
:lo World
:"
```

It's equivalent to writing 
```bbj
PRINT "Hello World"
````

in one single line.
