### ISSUE TITLE
readrecord etc

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#35]
the "one-word" variant is always flagged as an error:

```
readrecord = read record
writerecord = write record
extractrecord = extract record
printrecord = print record
```

**Comment by dhuebner** [comment]
@StephanWald
`readrecord = 6` works.
If `readrecord` is a variable, could you please elaborate what `= read record` is?

**Comment by StephanWald** [comment]
That's a pecularity of the language, in theory developers are not encouraged to use reserved keywords as variables. but they could, like this silly example illustrated:

```
LET PRINT=INPUT
IF PRINT>READRECORD THEN LET THEN=7
PRINT READRECORD
```

Having said that, readrecord is equivalent to read record:

```
READ RECORD X$
READRECORD Y$
```

I'd be okay with not including READRECORD as a keyword for now, as it's not officially documented but legacy behavior that might not be encouraged in new code.

**Comment by insafuhrmann** [comment]
From Meeting September 1st 2023:
Make READRECORD a new verb (keyword, OK that we get an error if used as variable name etc.).

**Comment by insafuhrmann** [comment]
@StephanWald Should [this](https://github.com/BBx-Kitchen/bbj-language-server/issues/35#issuecomment-1702496608) also be done for the other cases named above (writerecord, extractrecord, printrecord)? And is there the same issue for find and input (findrecord, inputrecord)?

**Comment by StephanWald** [comment]
yes, they all follow the same rule.
