### ISSUE TITLE
MODE= in FILEOPEN is flagged with warning

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#38]
```

serverfile$ = fileopen("Open Server File","","","",filter$,mode="server")
```

we may also check the other options of FILEOPEN and FILESAVE:

https://documentation.basis.cloud/BASISHelp/WebHelp/commands/fileopen_function_create_file_open_dialog.htm
https://documentation.basis.cloud/BASISHelp/WebHelp/commands/filesave_function_create_a_file_save_dialog.htm

**Comment by dhuebner** [comment]
- Fix library definition of FILEOPEN and FILESAVE in `functions.ts` by giving the param names where possible
- Adjust scoping to link against named function parameter

**Comment by dhuebner** [comment]
@StephanWald 
Fixed in master. 
What is the idea behind having `mode` and `MODE` parameter?

**Comment by StephanWald** [comment]
The "MODE=" pattern can be found across the BBj language in many places. It is used whenever a single or set of stringly parameters can be passed. Sometimes, the values that go inside are well-known and predetermined, sometimes they're passed to the underlying Java or OS environment (think of printer channels and spoolers, e.g.)

mode= is equal to MODE= is equal to mOdE= , IOW it's case insensitive like pretty much anything in the language (language, not BBjAPI methods which are in reality Java classes and methods, hence case sensitive)

**Comment by dhuebner** [comment]
@StephanWald 
What is not clear to me is that `fileopen` has two `mode` parameters. One lower and other upper case:
`FILEOPEN(prompt,path,name,ext[,filters[,mode[,MODE="CLIENT,EXISTS=option,RESOLVE=option,STYLE=name"]])`

I assume the `mode` parameter of type `int`  was replaced bei the `MODE` of type string? Or are they both present and valid in BBj 7.0 and higher?

**Comment by StephanWald** [comment]
Oh, I see.

See https://documentation.basis.cloud/BASISHelp/WebHelp/commands/fileopen_function_create_file_open_dialog.htm

mode (lowercase) is a direct parameter that can be 0,1, or 2, while "MODE=" is the "usual" MODE string I tried to explain before.

In the docs it says for "mode":

In BBj 5.0 and higher, select whether file, directories, or files and directories are selectable using the file dialog. The available options for mode are:

0 only files may be selected

1 only directories may be selected

2 files or directories may be selected

Note: The default setting is 0. When setting mode to 1 or 2, the filters option is ignored._

**Comment by dhuebner** [comment]
@StephanWald 
I see. So we can keep the definition in the function library as is. Thanks! 
So we can close this one.
