### ISSUE TITLE
WRITE, PRINT etc have parameters 

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#41]
```
write record (7) image$
read (6,key="TEST",DOM=*next)test$,test1$
```

**Comment by dhuebner** [comment]
For `PrintValue` parser rule from `WRITE {(channelno{options})}{outputlist}` `channelno` and `options` are missing.

See Options section:

https://documentation.basis.cloud/BASISHelp/WebHelp/commands/read_verb.htm

**Comment by Lotes** [comment]
@dhuebner It looks like that you have already handled this VERB. Look at [these lines](https://github.com/BBx-Kitchen/bbj-language-server/blob/4b3c8761a35f5e86475544474831a5e9dedc8933/bbj-vscode/src/language/bbj.langium#L252C1-L258C2).
Can we close this issue? Or am I missing something?

**Comment by dhuebner** [comment]
@Lotes 
If there are also tests for that already, we can close it

**Comment by Lotes** [comment]
@dhuebner I added some parser test cases inside of #137 . It covers the parameters given on the verb page, but yet nothing about formatted strings.
@StephanWald I saw some examples for `PRINT` formatting text. Is it ok to write it like `PRINT 123:"0000"` or do we always use `PRINT STR(123:"0000")`. For my understanding both is valid. See the WRITE verb documentation [here](https://documentation.basis.cloud/BASISHelp/WebHelp/commands/write_verb.htm).

**Comment by Lotes** [comment]
Thanks to Dennis, the string formatting is already part of the language.
But a few things still do not work currently:

```basic
REM TODO Format of IP:Port not documented well enough
WRITE (0, KEY="127.0.0.1") "ip-value"
WRITE (0, KEY="127.0.0.1":8080) "ip-value"
PRINT (0) strings$[ALL]
PRINT (0) IOL=JumpLabel
```

@StephanWald Can you give an example for KEY=<ip>:<port>. There was no sufficient example in the docs. What is its actual syntax?

**Comment by StephanWald** [comment]
For the IP see https://documentation.basis.cloud/BASISHelp/WebHelp/usr/socket_overview.htm
These samples work all fine. So closing this issue, we'll open concrete ones if other details still don't function correctly
