### ISSUE TITLE
READ, READ RECORD, EXTRACT, EXTRACT RECORD initialize variables

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#42]
There is a warning about test$ and test1$ not being initialized, but the read will actually initialize them:
```
read (6,key="TEST",DOM=*next)test$,test1$
````

**Comment by dhuebner** [comment]
@StephanWald 
Would be suppressing the linking warning here enough?

**Comment by insafuhrmann** [comment]
From meeting September 1st 2023:
Ignoring linking error is OK (at least for now).
Make sure next line can access test$.

**Comment by dhuebner** [comment]
Also FIND

**Comment by dhuebner** [comment]
@StephanWald 
I decided to create a synthetic local variable instead of swallowing a linking error. Works much better that way as you now can navigate to this variables when using them later.
