### ISSUE TITLE
support argument lists in code completion for BBj class methods 

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#47]
```
class public Sample
    method public String write(String dr!)
    methodend
classend

a!=new Sample()
a!.w
```

![image](https://github.com/BBx-Kitchen/bbj-language-server/assets/4833070/9bd8acf6-fff5-472c-ab56-05fdd2f16eb5)

**Comment by dhuebner** [comment]
@StephanWald 
Is it only about the content assist label? You expect to see `write(String dr!)`?

**Comment by dhuebner** [comment]
@StephanWald 
It look now like the following:
<img width="885" alt="Bildschirmfoto 2023-08-31 um 15 49 32" src="https://github.com/BBx-Kitchen/bbj-language-server/assets/454322/108497f1-26a7-4ea3-ab57-be96ac03bae9">
