### ISSUE TITLE
Offer Arguments of Java Classes in Code Completion

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#49]

**Comment by StephanWald** [comment]
![image](https://github.com/BBx-Kitchen/bbj-language-server/assets/4833070/6bb27370-163b-4149-b14e-813426b36d28)

```
use java.util.HashMap
hm! = new HashMap()
hm!.pu
```

**Comment by dhuebner** [comment]
Check if we have parameter information from java already.
See also  #47

**Comment by dhuebner** [comment]
@StephanWald 

Works almost the same way as for #47. 
Return type is also shown. 

<img width="938" alt="Bildschirmfoto 2023-08-31 um 15 53 04" src="https://github.com/BBx-Kitchen/bbj-language-server/assets/454322/c1942952-3838-4b3d-8d63-9abfb45db81b">
