### ISSUE TITLE
implement missing verbs

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#53]
some verbs simply seem to be still missing, so doing this catchall - issue, like for:

```
BEGIN

CLEAR 

BEGIN EXCEPT X$

ESCAPE

DROP A$
```

https://documentation.basis.cloud/BASISHelp/WebHelp/commands/Alphabetical_Verbs.htm

**Comment by StephanWald** [comment]
```
enter a$,b
```

**Comment by dhuebner** [comment]
For `DROP` see also #52

**Comment by insafuhrmann** [comment]
Have a look at the missing verbs, if it is a large number it might be a good idea to pick some as examples so that the rest of the work can be done by someone else. See whether there are some good learning examples.

**Comment by dhuebner** [comment]
`REPEAT` and  `UNTIL` is also missing

**Comment by dhuebner** [comment]
`VKEYED`

**Comment by dhuebner** [comment]
`setopts`

**Comment by SebastianAdams** [comment]
`PRECISION 16`

See:
https://documentation.basis.cloud/BASISHelp/WebHelp/commands/precision_verb.htm

**Comment by dhuebner** [comment]
@StephanWald 
Verbs from the initial [massage](https://github.com/BBx-Kitchen/bbj-language-server/issues/53#issue-1836623994) are implemented now.

**Comment by dhuebner** [comment]
All verbs except `VKEYED` are added  now

**Comment by StephanWald** [comment]
What is so special about VKEYED? Syntax is very similar if not equal to MKEYED and XKEYED.

**Comment by dhuebner** [comment]
@StephanWald 
Nothing really special. I just saw the `VKEYED` was missing in some of the example projects I have and yes, MKEYED and XKEYED are almost the same.  There was not enough time to implement it yesterday,
I plan to work on it today.

**Comment by Lotes** [comment]
@dhuebner All verbs mentioned here are already part of the grammar. Can we close this issue?

I started a table with one verb in each row that we could use to implement or prioritize the remaining missing verbs. I suggest to create one issue per missing verb row, so that @StephanWald can prioritize them. WDYT?

**Comment by Lotes** [comment]
Closed, because 'every mentioned verb' was already implemented and tested.
