### ISSUE TITLE
support access to array members

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#61]
```
DIM X[19,3]
X[1,3]=12

dim Y$[10]
y$[1](2,1)="TEST"
```

**Comment by dhuebner** [comment]
- `X[1,3]=12` allow array elements be the left side of assignment  
- `y$[1](2,1)="TEST"` allow substing on array elements

**Comment by dhuebner** [comment]
The example mentioned above are working now.
