### ISSUE TITLE
REM : line and block comments shortcuts are not working in vscode

### ISSUE THREAD

**Issue by hyyan** [BBx-Kitchen/bbj-language-server#73]
https://github.com/BBx-Kitchen/bbj-language-server/assets/4313420/c9e3f1a0-03ec-4281-8258-117dc82bbd60

**Comment by dhuebner** [comment]
@hyyan 
Block comments are not supported in BBx because a block comment need a start and end char sequence. I will enable single line comments for now.

**Comment by hyyan** [comment]
> Block comments are not supported in BBx because a block comment need a start and end char sequence

BBx part is understood. The starting sequence is `rem /**` and the end one is `  rem  */`

**Comment by dhuebner** [comment]
@hyyan 
Will following code be accepted as multiline comment in your runtime?

```vb
rem /**
Here is a
multiline comment
rem */
```

**Comment by hyyan** [comment]
> @hyyan Will following code be accepted as multiline comment in your runtime?
> 
> ```vbnet
> rem /**
> Here is a
> multiline comment
> rem */
> ```

No. comment lines should start with `REM`. The block comment is tricky and requires defining [onEnterRules](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules)

**Comment by hyyan** [comment]
@dhuebner We have that working in Eclipse and we got it working in vscode before  by using something like that. Even though it is not 100% optimal. Maybe we can use that as a start and improve it ?

```json
{
  "comments": {
    "lineComment": "rem",
    "blockComment": [
      "rem /**",
      "rem  */"
    ]
  },
  "onEnterRules": [
    {
      "beforeText": "^\\s*rem\\s*\\/\\*\\*(?!\\/)([^\\*]|\\*(?!\\/))*$",
      "action": {
        "indent": "indentOutdent",
        "appendText": "rem  *  "
      }
    },
    {
      "beforeText": "^\\s*rem\\s*\\*[^\\/].*$",
      "action": {
        "indent": "none",
        "appendText": "rem  *  "
      }
    },
    {
      "beforeText": "^\\s*rem[^\\*]$",
      "action": {
        "indent": "none",
        "appendText": "rem "
      }
    }
  ]
}
```

**Comment by dhuebner** [comment]
@hyyan 
Sure! Would you like to open a PR? 
Here is the config file: https://github.com/BBx-Kitchen/bbj-language-server/blob/main/bbj-vscode/language-configuration.json

**Comment by hyyan** [comment]
@dhuebner I'll prepare one
