### ISSUE TITLE
Missing comments/documentation on hover and auto-completion

### ISSUE THREAD

**Issue by hyyan** [BBx-Kitchen/bbj-language-server#75]
When properties , methods, interfaces and classes are hovered, comments should be showed. Same on auto-completion

**Comment by dhuebner** [comment]
@hyyan 
> When properties , methods, interfaces and classes are hovered, comments should be showed. Same on auto-completion

Do you mean Java or BBj?

**Comment by hyyan** [comment]
> @hyyan
> 
> > When properties , methods, interfaces and classes are hovered, comments should be showed. Same on auto-completion
> 
> Do you mean Java or BBj?

Both with BBj having the higher priority

**Comment by dhuebner** [comment]
@hyyan 
For BBj it is working now `typefox-dev` branch:

<img width="620" alt="Bildschirmfoto 2024-08-22 um 13 42 46" src="https://github.com/user-attachments/assets/12cb6356-28ef-4f49-a2fa-1a59c294b9aa">

Compiled Java classes do not include sources so do not include comments. For Java there is a Javadoc support implemented (not finished) based on *.json files.

**Comment by StephanWald** [comment]
General implementation done. There are remaining detail issues reported separately, closing this umbrella issue for clarity.
