### ISSUE TITLE
Support single line switch case statements

### ISSUE THREAD

**Issue by SebastianAdams** [BBx-Kitchen/bbj-language-server#81]
When using switch cases, single line commands in the "case" statement are valid and should not produce errors. Currently, the code below produces the following error: "This line needs to be wrapped by line breaks."

```
a$ = "2"

switch a$
    case "1"; print "First"; break
    case "2"; print "Second"; break
    case "3"; print "Third"; break    
    case default; print "Not in top three, try again"
swend
```

**Comment by dhuebner** [comment]
Should work as expected now. Please re-open if something is still missing.
