### ISSUE TITLE
Could not resolve reference to NamedElement named 'ESCAPE'

### ISSUE THREAD

**Issue by hyyan** [BBx-Kitchen/bbj-language-server#88]
Support the Escape verb.

https://documentation.basis.cloud/BASISHelp/WebHelp/commands/escape_verb.htm

```
? "before"
ESCAPE
? "after"
```

**Comment by dhuebner** [comment]
We have already an issue for `ESCAPE` #88

**Comment by hyyan** [comment]
#53

**Comment by dhuebner** [comment]
@hyyan 
Thanks! I fixed my comment.
