### ISSUE TITLE
linking-error on CAST statements

### ISSUE THREAD

**Issue by SebastianAdams** [BBx-Kitchen/bbj-language-server#89]
Use the [CAST](https://documentation.basis.cloud/BASISHelp/WebHelp/commands/cast_function_.htm) function's first parameter to determine the type of the object and offer code completion accordingly. 

In the following example, the CAST function is used to cast the first object from the vector into a HashMap, therefore the code assist should offer methods as for a HashMap. Instead, a linking-error is shown: 

``` vb
use java.util.HashMap

declare BBjVector vector!
vector! = new BBjVector()
vector!.add(new HashMap())

rem Could not resolve reference to ClassMember named 'put'.bbj(linking-error)
cast(HashMap, vector!.get(0)).put("Demo")
```

**Comment by dhuebner** [comment]
We could introduce a generic type for scalar library function. 
`CAST(param: T, param: object, ERR?:lineref): T` 
... or just hardcode `CAST` in type computation.

**Comment by dhuebner** [comment]
Fixed in `typefox-dev` branch
