### ISSUE TITLE
initializing a variable with null() breaks later discovery of types

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#92]
In the following example 

```
tc!=null()
tc! = BBjAPI().getThinClient()
clientfs! = tc!.getClientFileSystem()
```

the getClientFileSystem() gets flagged. If you remove the first line assigning tc!=null() then all works as expected.
Probably an initialization with null() should simply be ignored for the type discovery?

**Comment by dhuebner** [comment]
Note: this will also make scoping->linking->build slower.

**Comment by StephanWald** [comment]
declare needs to be used in that case
