### ISSUE TITLE
Is it OK that it is possible to call a method with a param that has not been declared?

### ISSUE THREAD

**Issue by insafuhrmann** [BBx-Kitchen/bbj-language-server#93]
At the moment it is possible to use variables that have not been declared as parameters in functions. This will not be flagged as an error in the current state.

@StephanWald @hyyan @SebastianAdams Is that OK? Will it be handled somehow?

**Comment by StephanWald** [comment]
Yes. Declaring and even initialization is always optional, also for variables you pass into a method CALL.

**Comment by insafuhrmann** [comment]
Thanks for the info!
